#!/bin/bash

# Nerd Font Icon Style Demonstration
# Shows stylistic differences between icon categories

echo "🎨 NERD FONT ICON STYLES DEMONSTRATION"
echo "====================================="
echo ""

echo "📝 nf-cod (Code/Codium) - Minimalist Line Art"
echo "Style: Clean, geometric, monoline, technical"
echo "Examples:"
echo -e "  Arrow:      \uf0a3  (nf-cod-arrow_down)"
echo -e "  File:       \uf102  (nf-cod-file_code)"
echo -e "  Search:     \uf98d  (nf-cod-search)"
echo -e "  Settings:   \uf085  (nf-cod-settings_gear)"
echo ""

echo "💻 nf-dev (Development) - Brand Recognition"
echo "Style: Detailed, brand-specific, varied complexity"
echo "Examples:"
echo -e "  GitHub:     \uf308  (nf-dev-git)"
echo -e "  Docker:     \uf308  (nf-dev-docker)"
echo -e "  Node.js:    \uf308  (nf-dev-nodejs)"
echo -e "  Python:     \uf328  (nf-dev-python)"
echo ""

echo "🎯 nf-fa (Font Awesome) - Classic Iconography"
echo "Style: Balanced, traditional, moderate detail"
echo "Examples:"
echo -e "  User:       \uf007  (nf-fa-user)"
echo -e "  Home:       \uf015  (nf-fa-home)"
echo -e "  Check:      \uf058  (nf-fa-check_circle)"
echo -e "  Star:       \uf005  (nf-fa-star)"
echo ""

echo "📱 nf-md (Material Design) - Rounded & Friendly"
echo "Style: Soft edges, consistent geometry, Google's design language"
echo "Examples:"
echo -e "  Account:    \uf004  (nf-md-account)"
echo -e "  Settings:   \uf493  (nf-md-settings)"
echo -e "  Folder:     \uf07b  (nf-md-folder)"
echo -e "  Heart:      \uf004  (nf-md-heart)"
echo ""

echo "🐙 nf-oct (Octicons) - GitHub's Design System"
echo "Style: Minimalist, precise, monoline, GitHub-specific"
echo "Examples:"
echo -e "  Mark:       \uf03c  (nf-oct-mark_github)"
echo -e "  Issue:      \uf026  (nf-oct-issue_opened)"
echo -e "  Pull Req:   \uf098  (nf-oct-git_pull_request)"
echo -e "  Repo:       \uf001  (nf-oct-repo)"
echo ""

echo "⚡ nf-iec (Electrical) - Technical Symbols"
echo "Style: Precise, technical, standardized electrical symbols"
echo "Examples:"
echo -e "  Power:      \uf204  (nf-iec-power)"
echo -e "  Ground:     \uf203  (nf-iec-ground)"
echo -e "  Battery:    \uf244  (nf-iec-battery_0)"
echo -e "  Signal:     \uf012  (nf-iec-signal)"
echo ""

echo "🌟 Style Comparison Summary:"
echo "================================"
echo "Minimal → Cod, Octicons (cleanest)"
echo "Balanced → FA (classic icons)"
echo "Friendly → MD (rounded, soft)"
echo "Detailed → Dev (brand recognition)"
echo "Technical → IEC (precision symbols)"
echo ""