#!/bin/bash

# ===================================
# Starship Configuration Builder
# ===================================
# This script assembles complete Starship configurations from modular components

set -euo pipefail

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Configuration files directory
CONFIG_DIR="$HOME/.config"

# Modes to build
MODES=("compact" "standard" "verbose" "gruvbox-rainbow")

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to extract module names from a TOML file
extract_module_names() {
    local file="$1"
    if [[ -f "$file" ]]; then
        grep -o '^\[[^]]*\]' "$file" | sed 's/^\[\(.*\)\]$/\1/' | sort
    fi
}

# Function to filter module file by excluding specified modules
filter_module_file() {
    local file="$1"
    local temp_file="$2"
    shift 2
    local exclude_modules=("$@")

    if [[ ! -f "$file" ]]; then
        return 0
    fi

    # If no modules to exclude, copy entire file
    if [[ ${#exclude_modules[@]} -eq 0 ]]; then
        cp "$file" "$temp_file"
        return 0
    fi

    # Create a pattern to match excluded modules
    local exclude_pattern=""
    for module in "${exclude_modules[@]}"; do
        if [[ -n "$exclude_pattern" ]]; then
            exclude_pattern="$exclude_pattern|"
        fi
        exclude_pattern="$exclude_pattern^\\[$module\\]"
    done

    # Filter out excluded sections
    awk -v pattern="$exclude_pattern" '
    /^[[:space:]]*\[/ {
        if ($0 ~ pattern) {
            skip = 1
            next
        } else {
            skip = 0
        }
    }
    !skip { print }
    ' "$file" > "$temp_file"
}

# Function to build a single configuration
build_config() {
    local mode="$1"
    local output_file="${mode}.toml"

    log_info "Building $mode configuration..."

    # Create temporary file
    local temp_file=$(mktemp)
    trap "rm -f $temp_file" RETURN

    # Start with schema and header
    cat > "$temp_file" << EOF
# ===================================
# Starship $(echo "${mode}" | sed 's/.*/\u&/') Mode Configuration
# ===================================
# Generated by build-configs.sh - DO NOT EDIT DIRECTLY
# Edit the modular components instead and rebuild

# Get editor completions based on the config schema
"\$schema" = 'https://starship.rs/config-schema.json'

EOF

    # Add format-specific configuration
    if [[ -f "formats/${mode}-format.toml" ]]; then
        log_info "  Adding format configuration..."
        cat "formats/${mode}-format.toml" >> "$temp_file"
        echo "" >> "$temp_file"
    else
        log_error "  Format file not found: formats/${mode}-format.toml"
        return 1
    fi

    # Get modules that will be overridden
    local override_file="modes/${mode}-overrides.toml"
    local overridden_modules=()
    if [[ -f "$override_file" ]]; then
        log_info "  Analyzing override file..."
        while IFS= read -r module; do
            overridden_modules+=("$module")
        done < <(extract_module_names "$override_file")
    fi

    # Add shared modules in logical order
    local modules=(
        "core-base.toml"              # Character (never overridden)
        "language-modules.toml"       # Language modules
        "container-modules.toml"      # Container tools
        "platform-modules.toml"      # Custom platform modules
        "system-modules.toml"         # System info modules
        "base-modules.toml"           # Status and local IP
        "github-modules.toml"         # GitHub integration modules
        "core-overridable.toml"       # Core modules that may be overridden
    )

    for module in "${modules[@]}"; do
        if [[ -f "modules/$module" ]]; then
            log_info "  Adding module: $module"
            # Filter out modules that will be overridden
            local module_temp=$(mktemp)
            trap "rm -f $module_temp" RETURN
            if [[ ${#overridden_modules[@]} -gt 0 ]]; then
                filter_module_file "modules/$module" "$module_temp" "${overridden_modules[@]}"
            else
                cat "modules/$module" > "$module_temp"
            fi
            cat "$module_temp" >> "$temp_file"
            echo "" >> "$temp_file"
        else
            log_warning "  Module not found: modules/$module"
        fi
    done

    # Add mode-specific overrides
    if [[ -f "$override_file" ]]; then
        log_info "  Adding ${mode} mode overrides..."
        cat "$override_file" >> "$temp_file"
        echo "" >> "$temp_file"
    else
        log_warning "  Override file not found: $override_file"
    fi

    # Add footer comment
    cat >> "$temp_file" << EOF

# ===================================
# Configuration Notes
# ===================================
# This configuration is automatically generated from modular components:
# - formats/${mode}-format.toml: Format and basic settings
# - modules/*: Shared module configurations
# - modes/${mode}-overrides.toml: Mode-specific customizations
#
# To modify this configuration, edit the source files and run:
# $ ./build-configs.sh
EOF

    # Move temporary file to final location
    mv "$temp_file" "$output_file"
    log_success "  Built $output_file"
}

# Function to validate configuration file
validate_config() {
    local config_file="$1"

    log_info "  Validating $config_file..."

    # Basic TOML syntax check using Python if available
    if command -v python3 &> /dev/null; then
        if python3 -c "
import tomllib
try:
    with open('$config_file', 'rb') as f:
        tomllib.load(f)
    print('✓ TOML syntax valid')
except Exception as e:
    print(f'✗ TOML syntax error: {e}')
    exit(1)
" 2>/dev/null; then
            log_success "  TOML syntax validation passed"
        else
            log_warning "  TOML syntax validation failed"
        fi
    else
        log_warning "  Python3 not available for TOML validation"
    fi
}

# Function to install configuration
install_config() {
    local mode="$1"
    local config_file="${mode}.toml"

    if [[ -f "$config_file" ]]; then
        log_info "Installing $config_file to modes/ directory..."
        cp "$config_file" "modes/$config_file"
        log_success "  Installed modes/$config_file"
    else
        log_error "  Configuration file not found: $config_file"
        return 1
    fi
}

# Main build function
build_all() {
    log_info "Starting Starship configuration build..."

    # Check if required directories exist
    for dir in formats modules modes; do
        if [[ ! -d "$dir" ]]; then
            log_error "Required directory not found: $dir"
            exit 1
        fi
    done

    # Build each mode
    local built_configs=()
    for mode in "${MODES[@]}"; do
        echo ""
        log_info "Building configuration for mode: $mode"
        if build_config "$mode"; then
            validate_config "${mode}.toml"
            install_config "$mode"
            built_configs+=("${mode}.toml")
        else
            log_error "Failed to build $mode configuration"
        fi
    done

    echo ""
    log_success "Build completed!"
    log_info "Built configurations: ${built_configs[*]}"

    # Show summary
    echo ""
    echo "Generated files:"
    for config in "${built_configs[@]}"; do
        echo "  - $config"
        if [[ -f "modes/$config" ]]; then
            echo "    → modes/$config"
        fi
    done

    echo ""
    log_info "To switch modes, use one of the following commands:"
    echo "  starship-compact   # Switch to compact mode"
    echo "  starship-standard  # Switch to standard mode"
    echo "  starship-verbose   # Switch to verbose mode"
    echo "  starship-gruvbox-rainbow # Switch to gruvbox-rainbow mode"
    echo ""
    log_info "Or manually update the symlink:"
    echo "  ln -sf \$(pwd)/modes/compact.toml   ~/.config/starship.toml"
    echo "  ln -sf \$(pwd)/modes/standard.toml  ~/.config/starship.toml"
    echo "  ln -sf \$(pwd)/modes/verbose.toml   ~/.config/starship.toml"
    echo "  ln -sf \$(pwd)/modes/gruvbox-rainbow.toml ~/.config/starship.toml"
}

# Function to clean old configurations
clean() {
    log_info "Cleaning old generated configurations..."

    for mode in "${MODES[@]}"; do
        local config_file="${mode}.toml"
        if [[ -f "$config_file" ]]; then
            rm "$config_file"
            log_info "  Removed $config_file"
        fi
    done

    log_success "Clean completed"
}

# Function to show help
show_help() {
    echo "Starship Configuration Builder"
    echo ""
    echo "Usage: $0 [COMMAND]"
    echo ""
    echo "Commands:"
    echo "  build    Build all configurations (default)"
    echo "  clean    Remove generated configuration files"
    echo "  help     Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0              # Build all configurations"
    echo "  $0 build        # Build all configurations"
    echo "  $0 clean        # Clean generated files"
}

# Main execution
main() {
    local command="${1:-build}"

    case "$command" in
        "build"|"")
            build_all
            ;;
        "clean")
            clean
            ;;
        "help"|"-h"|"--help")
            show_help
            ;;
        *)
            log_error "Unknown command: $command"
            show_help
            exit 1
            ;;
    esac
}

# Run main function with all arguments
main "$@"